apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-ziraat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-ziraat-api
  template:
    metadata:
      labels:
        app: hello-ziraat-api
    spec:
      containers:
        - name: hello-ziraat-api
          image: mervecakir/hello-ziraat-api:latest
          ports:
            - containerPort: 11130   
          resources:
            requests:
              cpu: "20m"
            limits:
              cpu: "100m"
