apiVersion: v1
kind: Service
metadata:
  name: hello-ziraat-api-service
spec:
  type: NodePort
  selector:
    app: hello-ziraat-api
  ports:
    - port: 11130        
      targetPort: 11130 
      nodePort: 30080 