apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-ziraat-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-ziraat-api
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30
  