name: Ziraat DevOps CI/CD Pipeline
on:
  push:
    branches: [ "main" ]        # Run workflow when code is pushed to main branch
  workflow_dispatch:             # Allow manual trigger from GitHub Actions UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest       # Runner environment

    steps:

      # Step 1 — Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2 — Set up Docker Buildx (build tool)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3 — Login to Docker Hub using secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4 — Build & push API image
      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: ./src/HelloZiraat.Api          # API project folder
          file: ./src/HelloZiraat.Api/Dockerfile  # API Dockerfile path
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/hello-ziraat-api:latest

      # Step 5 — Build & push Web image
      - name: Build and push Web image
        uses: docker/build-push-action@v6
        with:
          context: ./src/HelloZiraat.Web          # Web project folder
          file: ./src/HelloZiraat.Web/Dockerfile  # Web Dockerfile path
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/hello-ziraat-web:latest
